### ISSUE TITLE
Enumerable is not implemented for nil

### ISSUE THREAD

**Issue by basilenouvellet** [api-hogs/bureaucrat#50] opened 2019-05-13 22:53 UTC
Hello all,

First of all, thank you for this work!

I have a trouble currently setting up Bureaucrat with Slate & Swagger in an Phoenix API.

When I run `DOC=1 mix test`, I get this error:

`
00:49:37.308 [error] GenServer #PID<0.3151.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashDict, Map, MapSet, File.Stream, Date.Range, HashSet, List, Range, Stream, Function, GenEvent.Stream, IO.Stream
    (elixir) /builddir/build/BUILD/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /builddir/build/BUILD/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.each/2
    (elixir) lib/enum.ex:775: anonymous fn/3 in Enum.each/2
    (stdlib) maps.erl:257: :maps.fold_1/3
    (elixir) lib/enum.ex:1956: Enum.each/2
    (bureaucrat) lib/bureaucrat/swagger_slate_markdown_writer.ex:287: Bureaucrat.SwaggerSlateMarkdownWriter.write_operations_for_tag/4
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
    (stdlib) maps.erl:257: :maps.fold_1/3
    (elixir) lib/enum.ex:1956: Enum.map/2
    (bureaucrat) lib/bureaucrat/formatter.ex:10: Bureaucrat.Formatter.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:suite_finished, 326751, nil}}
00:49:37.310 [error] Task #PID<0.3130.0> started from #PID<0.93.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.3151.0>, :normal, 30000)
    ** (EXIT) exited in: :sys.terminate(#PID<0.3151.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashDict, Map, MapSet, File.Stream, Date.Range, HashSet, List, Range, Stream, Function, GenEvent.Stream, IO.Stream
                (elixir) /builddir/build/BUILD/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
                (elixir) /builddir/build/BUILD/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
                (elixir) lib/enum.ex:3015: Enum.each/2
                (elixir) lib/enum.ex:775: anonymous fn/3 in Enum.each/2
                (stdlib) maps.erl:257: :maps.fold_1/3
                (elixir) lib/enum.ex:1956: Enum.each/2
                (bureaucrat) lib/bureaucrat/swagger_slate_markdown_writer.ex:287: Bureaucrat.SwaggerSlateMarkdownWriter.write_operations_for_tag/4
                (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
                (elixir) lib/enum.ex:769: Enum.each/2
                (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
                (stdlib) maps.erl:257: :maps.fold_1/3
                (elixir) lib/enum.ex:1956: Enum.map/2
                (bureaucrat) lib/bureaucrat/formatter.ex:10: Bureaucrat.Formatter.handle_cast/2
                (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
                (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
                (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:948: GenServer.stop/3
    (ex_unit) lib/ex_unit/event_manager.ex:24: anonymous fn/2 in ExUnit.EventManager.stop/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_unit) lib/ex_unit/event_manager.ex:23: ExUnit.EventManager.stop/1
    (ex_unit) lib/ex_unit/runner.ex:28: ExUnit.Runner.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &ExUnit.run/0
    Args: []
** (EXIT from #PID<0.93.0>) exited in: GenServer.stop(#PID<0.3151.0>, :normal, 30000)
    ** (EXIT) exited in: :sys.terminate(#PID<0.3151.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashDict, Map, MapSet, File.Stream, Date.Range, HashSet, List, Range, Stream, Function, GenEvent.Stream, IO.Stream
                (elixir) /builddir/build/BUILD/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
                (elixir) /builddir/build/BUILD/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
                (elixir) lib/enum.ex:3015: Enum.each/2
                (elixir) lib/enum.ex:775: anonymous fn/3 in Enum.each/2
                (stdlib) maps.erl:257: :maps.fold_1/3
                (elixir) lib/enum.ex:1956: Enum.each/2
                (bureaucrat) lib/bureaucrat/swagger_slate_markdown_writer.ex:287: Bureaucrat.SwaggerSlateMarkdownWriter.write_operations_for_tag/4
                (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
                (elixir) lib/enum.ex:769: Enum.each/2
                (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
                (stdlib) maps.erl:257: :maps.fold_1/3
                (elixir) lib/enum.ex:1956: Enum.map/2
                (bureaucrat) lib/bureaucrat/formatter.ex:10: Bureaucrat.Formatter.handle_cast/2
                (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
                (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
                (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
`

I have some **tags** in my *swagger.json* though.

Can I borrow some help?

**Comment by davidrichey** [comment] 2019-07-03 19:59
@BasileNouvellet did you ever find out the issue on this?

**Comment by OpakAlex** [comment] 2019-07-03 20:30
i will check this guys

**Comment by OpakAlex** [comment] 2019-07-03 20:31
will be good to have some small project to reproduce it. Then i can fix it.

**Comment by jangnezda** [comment] 2019-08-01 15:21
I've been experiencing the same issue after upgrading Elixir and Phoenix in one of my projects. After a quick look at the code it seems like the problem is in[phoenix_swagger](https://github.com/xerions/phoenix_swagger). It needs to catch up with newer Phoenix versions, because currently it generates swagger file that is missing stuff like routes and so on, and because of that the `Bureaucrat.SwaggerSlateMarkdownWriter` breaks.

Option 1: Write the swagger file by hand
Option 2: Wait for `phoenix_swagger` to catch up to new Phoenix versions.

**Comment by OpakAlex** [comment] 2019-08-01 15:24
yes, we can wait phoenix_swagger. Create one issue for them pls.

**Comment by jangnezda** [comment] 2019-08-01 15:54
There is already an [open issue](https://github.com/xerions/phoenix_swagger/issues/232) related to this. And it has been actually fixed in `master`, but the problem is that the newest `phoenix_swagger` package in Hex is 0.8.1, which is from July 2018 ...

In the meantime you could tell mix to pull the dependency from github:
```
{:phoenix_swagger, git: "https://github.com/xerions/phoenix_swagger.git", branch: "master"}
```
This will then work with `Bureaucrat` (I've tested it).

**Comment by gitsadiq** [comment] 2019-12-27 09:33
but still i am facing  the same issue

**Comment by OpakAlex** [comment] 2019-12-27 09:36
can you show your versions in mix.lock? @gitsadiq

**Comment by tomjoro** [comment] 2020-04-05 15:42
I had the same problem and fixed it by adding the phoenix_swagger to the compilers in mix.exs

> def project do
> [
>   ...
>   compilers: [:phoenix, :gettext] ++ Mix.compilers ++ [:phoenix_swagger],
>   ...
> end

**Comment by gitsadiq** [comment] 2020-04-25 00:56
That was the problems due to missing of input fields. after giving proper
fields i got the exact output but for larger projects
using slate becomes too hard. did't getting exact output also did't showing
what the exact problem was. i put on hold my feature branch
will try after completing project

**Comment by hugrave** [comment] 2021-03-01 17:02
I am experiencing the same problem. I have the swagger.json file attached here. Linking to the only operation_id available in the test case, I get the same error above. 

`{
  "definitions": {},
  "host": "localhost:4000",
  "info": {
    "title": "RestWorld",
    "version": "0.0.1"
  },
  "paths": {
    "/form": {
      "post": {
        "description": "Insert or update form data",
        "operationId": "form_insert_or_update",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Success"
          }
        },
        "summary": "",
        "tags": [
          "Forms"
        ]
      }
    }
  },
  "swagger": "2.0"
}`

**Closed** 2024-01-16 17:49 UTC
